### ISSUE TITLE
display Console button broken?

### ISSUE THREAD

**Issue by g-l-i-t-c-h-o-r-s-e** [BlueSquare23/web-lgsm#1]
When I click the `Console` button while my server is live, I get this error
> error connecting to /tmp/tmux-1003/default (No such file or directory)

**Comment by BlueSquare23** [comment]
What game server are you running? The console button doesn't actually work for all game servers because not all LGSM game servers have a console. For example for Battlefield 1942 there is no game server console.

I do have plans to address games like Battlefield 1942 where buttons like update and console do nothing. But I haven't gotten there yet.

**Comment by g-l-i-t-c-h-o-r-s-e** [comment]
I get this error on L4D2 and TF2 server

**Comment by BlueSquare23** [comment]
Okay I've just pushed a fix for this! Tested it for a couple of game servers and it appears to be working again. Let me know if you have any problems.

All you need to do is ssh to your server, cd to your web-lgsm directory, and run `git pull` to pull in the new changes. You might want to back up your `main.conf` before doing that (`cp main.conf main.conf.bak`) because git pull will overwrite that file if you've made any settings changes. A comprehensive update mechanism is coming in version 1.4, till then its just git pull.

Once again thanks for reporting this and let me know if you have any other issues!
