### ISSUE TITLE
Add Features - Edit files

### ISSUE THREAD

**Issue by thomasbonsirven** [BlueSquare23/web-lgsm#10]
Hello,

I was building a webpanel when I came across your github.

Well done, good job for this work.

I wanted to know if it was possible to set up a file editor for modifying the configuration of certain games.
For example, the palworld game, it would be very interesting to be able to modify the Palworld/serverfiles/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini file.
As well as modifying the ports or the game server launch command.

I'm ready to help you implement these functions

**Comment by BlueSquare23** [comment]
Yeah this already exists, however its disabled by default. If you edit the `main.conf` file and then set `cfg_editor` to yes it will enable the config editor. I'll go ahead and add the `PalWorldSettings.ini` file name to the accepted_cfgs.json now in order to enable palword server cfg file discovery. Let me know if you have any other questions!

**Comment by thomasbonsirven** [comment]
WooW
It's so effective, and so simple !
Good Job !
