### ISSUE TITLE
HTML remake

### ISSUE THREAD

**Issue by BenderBlenderCZE** [BlueSquare23/web-lgsm#12]
Hey Blue, i am a hobbyist in HTML and CSS and i could help you with the frontend and anything you would want, i know a lot of other languages but only a bit of them, i mainly know html and css, so if you would to contact me, text me using
 email: admin@socknet.eu
 discord: benderblende
 or simply reply to this, hope to see you soon

**Comment by BlueSquare23** [comment]
Cool yeah I welcome outside help as long as its good quality and makes sense and stuff! This project is a lot of Bootstrap 5 for css. Have you ever worked with Bootstrap before? Its not very hard to use, that's why I went with it.
https://getbootstrap.com/docs/5.0/getting-started/introduction/
https://www.youtube.com/watch?v=-qfEOE4vtxE

Tbh my approach to the frontend on this project has mostly been practical / pragmatic. Like mostly about just making something that works. I do try to make it look nice too but yeah my frontend skillz are a little weak.

All that to say if you see something on one of the pages that you think could be fixed up or made prettier, I'm all ears! If its just something small and you just want to submit a pull request we can work on it from there. Anything bigger we should probably discuss more first. Plus am one man so can only review pr's of a certain size. Think 'ship of Theseus' = good, 'remake whole ship at once' = bad.

Or let me know if you have any questions before jumping into development! We can communicate on here or through some other channel first to talk about changes or just how to use the app in dev mode. I'm down for that. If you've got some good ideas, we can get a pull request submitted to the latest dev branch!

Here's the current dev branch.
https://github.com/BlueSquare23/web-lgsm/tree/dev-beta-1.5

For python Flask apps the html is going to be down in the `templates` directory.
https://github.com/BlueSquare23/web-lgsm/tree/dev-beta-1.5/app/templates

You can find the css/js for the project down in the static dir.
https://github.com/BlueSquare23/web-lgsm/tree/dev-beta-1.5/app/static

If you run `./scripts/debug.py` from the main web-lgsm dir. That'll start the app in dev mode in your terminal! Let me know if you have any other questions.
