### ISSUE TITLE
Allow root

### ISSUE THREAD

**Issue by Not-Zero-Blank** [BlueSquare23/web-lgsm#18]
**Is your feature request related to a problem? Please describe.**
Im trying to deploy it in an LXC Container, but i dont want to create a new user

**Describe the solution you'd like**
Just allow the root user

**Comment by BlueSquare23** [comment]
So the problem is not really with my web app but rather with the underlying LGSM scripts themselves. Unfortunately, the LGSM scripts do Not support being run as root.

```
Minecraft» sudo ./linuxgsm.sh mcserver
[ FAIL ] Do NOT run as root!
```

So there's really nothing I can do to make this work, as this project is really just a web panel wrapper for the underlying LGSM shell scripts.
